### ISSUE TITLE
changing ENV variable RAGEMP_CSHARP to true dont work 

### ISSUE THREAD

**Issue by enricofranke** [BamButz/docker-ragemp#1]
hey so I have a question I'm setting the env variable `RAGEMP_CSHARP` to true but in the config file is not changed to enabled as it does on any other env variable 

see like this [screenshot](https://prnt.sc/r6mxiw)
in the test you can see in the screenshot I was changing the Announcement to `true` and in the config file it was changed to enabled that's what we want to happen but sadly it's not working for the c# as you can see it is still on true and not on enabled 

[thats the conifg](http://prntscr.com/r6n04u)

I was wondering if this is a bug or how I can basically enable c#?

if you wondering why I want to enable it's because of the c# bridge 

thanks for the answer in advance :D

**Comment by BamButz** [comment]
Hey,

if I am correct the container still needs the files for the bridge.
I added them blindly, can you check if it works now?

According to [RageMP Wiki](https://wiki.rage.mp/index.php?title=Server_settings) you have to set the csharp setting to true, but since the default value is 'disabled' you can also try 'enabled'.

Best wishes

**Comment by enricofranke** [comment]
Hey,

so the bridge is in the files good job but the problem is that with `true` it is not loading the bridge and with `enabled` I get this [error](https://prnt.sc/r6nsq2)

am I'm doing something wrong?
and I found this on a video with a working example from a Russian dude that I don't understand
[config](https://prnt.sc/r6ntv2) the video [link](https://www.youtube.com/watch?v=qHbJk6O4lM0&t=890s)

**Comment by BamButz** [comment]
Could you set the environment variable to "enabled" including the double quotes?
I will also look at it later the day.

**Comment by enricofranke** [comment]
so I set the environment variable to `" enabled"` with the double quotes this is the [result ](https://prnt.sc/r704t1) and this is how the [config](https://prnt.sc/r705ck) file locks like my guess would be that the double quotes are not getting recognized so what I did I tried to do double quotes like this `""enabled""` but this doesn't work as well so yea

**Comment by BamButz** [comment]
It works for me by escaping the variable as follows `-e RAGEMP_CSHARP=\"enabled\"` as you can see in this [screenshot](https://user-images.githubusercontent.com/7022144/75188625-be4bef80-574c-11ea-9f46-030da38e5d3e.png). I create a fix for the days, then you should be able to use the parameter again with true/false.

Thanks for reporting the problem
